packages:
  - 'packages/core'
  - 'packages/__tests__/project1'
  - 'packages/utils/vitest'

allowBuilds:
  esbuild: true

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/dev-utils@0.8.2'
