packages:
  - 'packages/hook-wrapper'
  - 'packages/__tests__/project1'
  - 'packages/utils/vitest'
  - 'apps/tan-react'

allowBuilds:
  esbuild: true

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/*'
